require('plugins')
require('key-mappings')
require('settings')
require('color-settings')

require('plugins-config/lspkind')
require('plugins-config/nvim-autopairs')
require('plugins-config/nvim-colorizer')
require('plugins-config/nvim-tree')
require('plugins-config/nvim-compe')
require('plugins-config/nvim-treesitter')
require('plugins-config/nvim-ts-autotag')
require('plugins-config/telescope')
require('plugins-config/telescope-customs')
require('plugins-config/vim-wiki')

require('lsp/lua-language-server')
